config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  get 'about', to: 'pages#about'

  get 'courses/new', to: 'courses#new'

  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'

  post 'course_enroll', to: 'student_courses#create'
  
  resources :students, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    validates :short_name, presence:  true, length: {minimum:3, maximum:15}
    validates :name, presence:  true, length: {minimum:5, maximum:50}
    validates :description, presence:  true, length: {minimum:10, maximum:100}

    has_many :student_courses
    has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
    before_save { self.email = email.downcase }

    validates :name, presence: true, length: { minimum:5, maximum:100 }

    # Una constante es en Mayúsculas
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
    
    has_secure_password

    has_many :student_courses
    has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
    belongs_to :student
    belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_user
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= Student.find(session[:student_id]) if session[:student_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:notice] = "No puedes realizar esta acción"
            redirect_to login_path
        end
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    skip_before_action :require_user
    
    def index
        @courses = Course.all
    end

    def new
        
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    skip_before_action :require_user, only: [:new, :create]

    def new

    end

    def create
        student = Student.find_by(email: params[:logins][:email].downcase)
        if student && student.authenticate(params[:logins][:password])
            session[:student_id] = student.id
            flash[:notice] = "Iniciaste sesión correctamente"
            redirect_to student
        else
            flash.now[:notice] = "Hubo un error en los datos ingresados"
            render 'new'
        end
    end

    def destroy
        session[:student_id] = nil
        flash[:notice] = "Cerraste sesión correctamente."
        redirect_to root_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :require_user

    def index
        
    end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController

    def create
        course_to_add = Course.find(params[:course_id])
        unless current_user.courses.include?(course_to_add)
            StudentCourse.create(course: course_to_add, student: current_user)
            flash[:notice] = "Felicidades, lograste inscribirte al curso #{course_to_add.name}"
            # Redireccionará a la vista del usuario actual
            redirect_to current_user
        else
            flash[:notice] = "Hubo un error en la inscripción del curso"
            redirect_to root_path
        end
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    skip_before_action :require_user, only: [:new, :create]
    before_action :set_student, only: [:show, :edit, :update, :destroy]
    before_action :require_same_user, only: [:edit, :update]

    def index
        @students = Student.all
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)
        if @student.save
            flash[:notice] = "Felicidades, tu registro fue exitoso"
            redirect_to login_path
        else
            render 'new'
        end
    end

    def show

    end

    def edit
        
    end

    def update
        if @student.update(student_params)
            flash[:notice] = "Felicidades, tus datos se actualizaron correctamente"
            redirect_to @student
            # redirect_to student_path(@student)
        else
            render 'edit'
        end
    end

    def destroy

    end


    private
        def student_params
            params.require(:student).permit(:name, :email, :password, :password_confirmation)
        end
        
        def set_student
          @student = Student.find(params[:id])
        end

        def require_same_user
            if current_user != @student
                flash[:notice] = "Solo puedes editar tus datos."
                redirect_to student_path(current_user)
            end
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h2 class="center-align">Lista de Cursos</h2>
  </div>
</div>
<div class="row">
  <% @courses.each do |course| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.short_name %> : <%= course.name %></span>
          <p><%= course.description %></p>
        </div>
        <div class="card-action">
          <% if logged_in? && !(current_user.courses.include?(course)) %>
            <%= link_to 'Inscribirse', course_enroll_path(course_id: course.id), method: :post %>
          <% end %>
          <a href="">Info</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav>
  <div class="nav-wrapper">
    <div class="container">
      <%= link_to 'University Technology', root_path, class: "brand-logo" %>
    </div>
    <a href="" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <% if logged_in? %>
        <li><%= link_to 'Cursos', root_path %></li>
        <li><%= link_to 'Estudiantes', students_path %></li>
        <li><a class="dropdown-trigger" data-target="dropdown1"><%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
        <!-- Menu desplegable -->
        <ul id="dropdown1" class="dropdown-content">
          <li><%= link_to 'Perfil', student_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to 'Cerrar Sesión', logout_path, method: :delete %></li>
        </ul>
        <!-- Menu desplegable -->
      <% else %>
        <li><%= link_to 'Iniciar Sesión', login_path, class: "btn blue" %></li>
        <li><%= link_to 'Registrarse', new_student_path, class: "btn success" %></li>
      <% end %>
    </ul>
    <%# -------------------------------------------------------------------- Mobile %>
    <ul class="sidenav" id="mobile-demo">
      <% if logged_in? %>
        <li><%= link_to 'Cursos', root_path %></li>
        <li><%= link_to 'Estudiantes', students_path %></li>
        <li><a class="dropdown-trigger" data-target="dropdown2"><%= current_user.email %><i class="material-icons">arrow_drop_down</i></a></li>
        <!-- Menu desplegable -->
        <ul id="dropdown2" class="dropdown-content">
          <li><%= link_to 'Perfil', student_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to 'Cerrar Sesión', logout_path, method: :delete %></li>
        </ul>
        <!-- Menu desplegable -->
      <% else %>
        <li><%= link_to 'Iniciar Sesión', login_path, class: "btn blue" %></li>
        <li><%= link_to 'Registrarse', new_student_path, class: "btn success" %></li>
      <% end %>
    </ul>
  </div>
</nav>
<% flash.each do |key,message| %>
  <div class="container">
    <div class="row center sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel green lighten-2" id="fade-out-target">
          <span class="white-text">
            <%= message %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniversityApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header">Iniciar Sesión</h3>
        <div class="row">
          <%= form_for(:logins, html: {class: "col s12"}) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :email, 'Correo Electrónico'%>
                <%= f.email_field :email, autofocus: true %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :password, 'Contraseña', class: "active" %>
                <%= f.password_field :password %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.button "Ingresar", class: "btn orange waves-effect waves-light right" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row center sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong><%= pluralize(obj.errors.count, "error") %></strong>
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= @student.new_record? ? "Nueva Cuenta" : "Editar Perfil" %></h3>
        <div class="row">
          <%= form_for(@student, html: {class: "col s12"}) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :name, 'Nombre' %>
                <%= f.text_field :name, autofocus: true %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :email, 'Correo Electrónico', class: "active" %>
                <%= f.email_field :email %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :password, 'Contraseña', class: "active" %>
                <%= f.password_field :password %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :password_confirmation, 'Confirmar Contraseña', class: "active" %>
                <%= f.password_field :password_confirmation %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.button(@student.new_record? ? "Registrate" : "Actualizar", class: "btn orange waves-effect waves-light right") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h2 class="center-align">Lista de Estudiantes</h2>
  </div>
</div>
<div class="row">
  <% @students.each do |student| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= student.name %></span>
          <p><%= student.email %></p>
        </div>
        <div class="card-action">
          <%= link_to 'Ver perfil', student_path(student) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row sign-up-form">
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= @student.name %></span>
        <p><%= @student.email %></p>
        <p>Cursos inscritos:
          <% if @student.courses.empty? %>
            Ninguno
          <% else %>
            <ul>
              <% @student.courses.each do |course| %>
                <li> => <%= course.name %></li>
              <% end %>
            </ul>
          <% end %>
        </p>
      </div>
    </div>
    <% if current_user == @student %>
      <%= link_to '<i class="material-icons right">create</i>Editar Perfil'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn" %>
    <% end %>
  </div>
</div>